"""Centralized configuration for the congestion simulator."""

from pathlib import Path

DEFAULT_HOST = "127.0.0.1"
DEFAULT_UDP_PORT = 9000
DEFAULT_TCP_PORT = 9001
DEFAULT_PACKET_SIZE = 1024
DEFAULT_CLIENTS = 5
DEFAULT_DURATION = 10
DEFAULT_SEND_INTERVAL = 0.05
DEFAULT_RATE_LIMIT = 200
DEFAULT_REPORT_INTERVAL = 1.0
DEFAULT_BUFFER_SIZE = 4096
DEFAULT_OUTPUT_DIR = Path("results")
DEFAULT_METRICS_FILE = DEFAULT_OUTPUT_DIR / "metrics.json"
